server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306?d_security
    username: root
    password: root
  security:
    user:
      password: 123456
      name: user
  thymeleaf:
    cache: false